name: algeria_eats
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  introduction_screen: ^3.1.12
  intl: ^0.19.0
  badges: ^3.1.2
  dio: ^5.4.0
  rive: ^0.12.4
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dzair_data_usage: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 16
  web:
    generate: false
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "assets/images/icon.png"
    icon_size: 48
  macos:
    generate: false
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/RiveAssets/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/Fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/Fonts/Inter-Black.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Poppins-Regular.ttf
          weight: 400
